import { Button, Text } from '@mantine/core'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
    <main>
      <Text>Hello!</Text>
      <Button>test</Button>
    </main>
    </div>
  )
}
